"""added a number of real estates column on users

Revision ID: d9d3ffcf04d7
Revises: 
Create Date: 2024-07-14 22:40:36.869950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d3ffcf04d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numberEstates', sa.Integer(), nullable=True, default=0))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('numberEstates')

    # ### end Alembic commands ###
